### ISSUE TITLE
Doesn't launch without the 'mount-observe' plug

### ISSUE THREAD

**Issue by Benedolt** [kz6fittycent/bpytop-snap#2]
Thanks for snapping this awesome app, James! 

For me bpytop won't launch at all without the 'mount-observe' plug. All other plugs seem to be optional. Error is as follows:

```
07/08/20 (16:37:30) | ERROR: Data collection thread failed with exception: [Errno 13] Permission denied: '/proc/partitions'
Traceback (most recent call last):
  File "/snap/bpytop/58/usr/bin/bpytop", line 2319, in _runner
    collector._collect()
  File "/snap/bpytop/58/usr/bin/bpytop", line 2602, in _collect
    io_counters = psutil.disk_io_counters(perdisk=True if SYSTEM == "Linux" else False, nowrap=True)
  File "/snap/bpytop/58/usr/lib/python3/dist-packages/psutil/__init__.py", line 2014, in disk_io_counters
    rawdict = _psplatform.disk_io_counters()
  File "/snap/bpytop/58/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1040, in disk_io_counters
    partitions = get_partitions()
  File "/snap/bpytop/58/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1022, in get_partitions
    with open_text("%s/partitions" % get_procfs_path()) as f:
  File "/snap/bpytop/58/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 201, in open_text
    return open(fname, "rt", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/partitions'
07/08/20 (16:37:30) | WARNING: Exiting with errorcode (1). Runtime 0:00:03 

```

**Comment by kz6fittycent** [comment]
Thanks for using the snap! I happened to find this developer via another Linux user and I love `bashtop` and `bpytop`, so I had to snap them. 

Whereas bpytop is using psutils and is looking for mount info, it would make sense that it'd run into errors on launch. Unfortunately, I don't know any way around this. Other plugs might provide similar information but require manual review from Canonical devs and would still require users to connect the interfaces - even then, I don't think it'd work without them (e.g. `raw-volume`). 

Have you tried connecting that plug?

`sudo snap connect bpytop:mount-observe` 

Here's the info on that plug, in case you're worried what it can do: https://snapcraft.io/docs/mount-observe-interface

**Comment by Benedolt** [comment]
Yeah, I love bashtop and bpytop is even sexier! :) I connected the `mount observe` plug and it works perfectly. I just wanted to bring to your attention that bpytop just doesn't start at all without that plug connected. All other plugs seem to be optional, i.e. bpytop starts up and works without them. (I don't test whether all functions are there though.)

As bpytop just errors out without the plug I believe it would be best to apply for auto-connecting `mount-observe`. Otherwise non-technical users might be lost when they try the app.

But I have no idea what the regulations for that are - I just wanted to raise the issue. ;) 

Thanks again for the awesome snap!
