### ISSUE TITLE
[FEATURE] Add the snap connect commands to the snap install

### ISSUE THREAD

**Issue by phlmike** [kz6fittycent/bpytop-snap#3]
Have it list the snap connect commands when it completes the snap install or have the install handle those automatically.

**Comment by kz6fittycent** [comment]
I think this is something that the user should handle - even the htop snap requires connecting some interfaces upon installation for more functionality. 

I can also see other users complaining that I "did" automatically connect them. Also, `snap info bpytop` shows what to do. 

That all said, thanks for using the snap and I hope you enjoy it!
