### ISSUE TITLE
i386 build crashes on startup

### ISSUE THREAD

**Issue by Benedolt** [kz6fittycent/bpytop-snap#9]
Hi James,

I know I'm an edge case here, but on my 32-bit system the bpytop snap crashes on launch with the following error:

```
  File "/snap/bpytop/116/usr/bin/bpytop", line 34
    errors: List[str] = []
          ^
SyntaxError: invalid syntax
```

Could you look into that. I'll be happy to test any new builds!

**Comment by kz6fittycent** [comment]
32-bit isn't supported on `core20` AFAIK. 

As far as the builds, I'm not even building `i386`

**Comment by kz6fittycent** [comment]
https://forum.snapcraft.io/t/sunsetting-strategy-for-i386-on-core20/19824

**Comment by Benedolt** [comment]
Ah, I see, i386 isn't even in the snapcraft.yaml anymore. I guess there's no way to have a 32-bit version built against the older core-package, right? If not, is it possible to delete the i386 build as it doesn't work?

**Comment by kz6fittycent** [comment]
I just tried deleting the i386 package. No go, sorry. Hopefully Canonical can get this kind of thing fixed, soon.

**Comment by Benedolt** [comment]
That's a shame, I got my hopes up that it would work. Anyway, thanks so much for packaging this snap, James! I love using it!
